--- #YAML:1.0
name:               VANAMBURG-SEMPROG-SimpleGraph
version:            0.009
abstract:           A Perl companion "Programming The Semantic Web"
author:
    - Gordon Van Amburg <vanamburg@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:             0
    List::MoreUtils:  0
    LWP::Simple:      0
    Modern::Perl:     1.03
    Moose:            0.93
    Moose::Role:      0
    Set::Scalar:      0
    Test::More:       0
    Text::CSV_XS:     0
    URI::Escape:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
